// Generated by gencpp from file delivery_robot/r_angle_optional.msg
// DO NOT EDIT!


#ifndef DELIVERY_ROBOT_MESSAGE_R_ANGLE_OPTIONAL_H
#define DELIVERY_ROBOT_MESSAGE_R_ANGLE_OPTIONAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <delivery_robot/r_angle.h>

namespace delivery_robot
{
template <class ContainerAllocator>
struct r_angle_optional_
{
  typedef r_angle_optional_<ContainerAllocator> Type;

  r_angle_optional_()
    : valid(false)
    , angle()  {
    }
  r_angle_optional_(const ContainerAllocator& _alloc)
    : valid(false)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef  ::delivery_robot::r_angle_<ContainerAllocator>  _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::delivery_robot::r_angle_optional_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_robot::r_angle_optional_<ContainerAllocator> const> ConstPtr;

}; // struct r_angle_optional_

typedef ::delivery_robot::r_angle_optional_<std::allocator<void> > r_angle_optional;

typedef boost::shared_ptr< ::delivery_robot::r_angle_optional > r_angle_optionalPtr;
typedef boost::shared_ptr< ::delivery_robot::r_angle_optional const> r_angle_optionalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_robot::r_angle_optional_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_robot::r_angle_optional_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delivery_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'delivery_robot': ['/home/rosvm/catkin_ws/src/delivery_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_angle_optional_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_angle_optional_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_angle_optional_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
{
  static const char* value()
  {
    return "728fa7476ca33a373cc4348c443648a2";
  }

  static const char* value(const ::delivery_robot::r_angle_optional_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x728fa7476ca33a37ULL;
  static const uint64_t static_value2 = 0x3cc4348c443648a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_robot/r_angle_optional";
  }

  static const char* value(const ::delivery_robot::r_angle_optional_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid\n\
r_angle angle\n\
\n\
================================================================================\n\
MSG: delivery_robot/r_angle\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::delivery_robot::r_angle_optional_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct r_angle_optional_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_robot::r_angle_optional_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_robot::r_angle_optional_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "angle: ";
    s << std::endl;
    Printer< ::delivery_robot::r_angle_<ContainerAllocator> >::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_ROBOT_MESSAGE_R_ANGLE_OPTIONAL_H
