// Generated by gencpp from file delivery_robot/r_battery.msg
// DO NOT EDIT!


#ifndef DELIVERY_ROBOT_MESSAGE_R_BATTERY_H
#define DELIVERY_ROBOT_MESSAGE_R_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <delivery_robot/r_current_optional.h>

namespace delivery_robot
{
template <class ContainerAllocator>
struct r_battery_
{
  typedef r_battery_<ContainerAllocator> Type;

  r_battery_()
    : voltage(0.0)
    , current_optional()  {
    }
  r_battery_(const ContainerAllocator& _alloc)
    : voltage(0.0)
    , current_optional(_alloc)  {
  (void)_alloc;
    }



   typedef double _voltage_type;
  _voltage_type voltage;

   typedef  ::delivery_robot::r_current_optional_<ContainerAllocator>  _current_optional_type;
  _current_optional_type current_optional;





  typedef boost::shared_ptr< ::delivery_robot::r_battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_robot::r_battery_<ContainerAllocator> const> ConstPtr;

}; // struct r_battery_

typedef ::delivery_robot::r_battery_<std::allocator<void> > r_battery;

typedef boost::shared_ptr< ::delivery_robot::r_battery > r_batteryPtr;
typedef boost::shared_ptr< ::delivery_robot::r_battery const> r_batteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_robot::r_battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_robot::r_battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delivery_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'delivery_robot': ['/home/rosvm/catkin_ws/src/delivery_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot::r_battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot::r_battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot::r_battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_robot::r_battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d5b2b7c86da965057d9d022bdda16f1";
  }

  static const char* value(const ::delivery_robot::r_battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d5b2b7c86da9650ULL;
  static const uint64_t static_value2 = 0x57d9d022bdda16f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_robot::r_battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_robot/r_battery";
  }

  static const char* value(const ::delivery_robot::r_battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_robot::r_battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 voltage\n\
r_current_optional current_optional\n\
\n\
================================================================================\n\
MSG: delivery_robot/r_current_optional\n\
bool valid\n\
float64 current\n\
";
  }

  static const char* value(const ::delivery_robot::r_battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_robot::r_battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
      stream.next(m.current_optional);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct r_battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_robot::r_battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_robot::r_battery_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "current_optional: ";
    s << std::endl;
    Printer< ::delivery_robot::r_current_optional_<ContainerAllocator> >::stream(s, indent + "  ", v.current_optional);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_ROBOT_MESSAGE_R_BATTERY_H
