local_costmap:
  global_frame: turtlebot_01_odom
  robot_base_frame: turtlebot_01_base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2.0

  static_map: false  
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  
